"""Versioned, dependency-free Forge Foundation Model contracts."""

from .foundation import (
    Capability,
    EngineeringMode,
    GovernanceProfile,
    KnowledgeAccessMode,
    KnowledgeLifecycle,
    KnowledgeSource,
    KnowledgeTrustClassification,
    Repository,
    RepositoryCatalog,
    RepositoryRole,
    Workspace,
)
from .planning import (
    EngineeringGoal,
    EngineeringIncrementProposal,
    EngineeringPlan,
    EvidenceKind,
    EvidenceReference,
    IncrementDependency,
    PlanStatus,
    RiskLevel,
)
from .proposal import (
    EngineeringProposal,
    ProposalCreationMetadata,
    ProposalDependencies,
    ProposalRationale,
    ProposalRisk,
    ProposalScope,
    ProposalStatus,
    RiskAssessment,
    transition_proposal,
)
from .prompt_artifact import (
    EngineeringPromptArtifact,
    ExecutionInstructions,
    PromptArtifactContext,
    PromptArtifactObjective,
    PromptArtifactScope,
    PromptArtifactStatus,
    SourceProposalReference,
    ValidationRequirements,
    transition_prompt_artifact,
)

__all__ = [
    "Capability",
    "EngineeringMode",
    "GovernanceProfile",
    "KnowledgeAccessMode",
    "KnowledgeLifecycle",
    "KnowledgeSource",
    "KnowledgeTrustClassification",
    "Repository",
    "RepositoryCatalog",
    "RepositoryRole",
    "Workspace",
    "EngineeringGoal",
    "EngineeringIncrementProposal",
    "EngineeringPlan",
    "EvidenceKind",
    "EvidenceReference",
    "IncrementDependency",
    "PlanStatus",
    "RiskLevel",
    "EngineeringProposal",
    "ProposalCreationMetadata",
    "ProposalDependencies",
    "ProposalRationale",
    "ProposalRisk",
    "ProposalScope",
    "ProposalStatus",
    "RiskAssessment",
    "transition_proposal",
    "EngineeringPromptArtifact",
    "ExecutionInstructions",
    "PromptArtifactContext",
    "PromptArtifactObjective",
    "PromptArtifactScope",
    "PromptArtifactStatus",
    "SourceProposalReference",
    "ValidationRequirements",
    "transition_prompt_artifact",
]
